"""Playable prototype scaffolding for common game stacks."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def scaffold_game_project(
    destination: Path,
    engine: str,
    title: str,
    *,
    assets: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Create a minimal playable prototype project."""
    engine_key = engine.lower().strip()
    destination.mkdir(parents=True, exist_ok=True)
    (destination / "assets").mkdir(exist_ok=True)
    (destination / "src").mkdir(exist_ok=True)
    assets = assets or []
    if engine_key in {"html", "canvas", "html5", "js"}:
        files = _scaffold_canvas(destination, title)
    elif engine_key == "phaser":
        files = _scaffold_phaser(destination, title)
    elif engine_key in {"three", "threejs", "three.js"}:
        files = _scaffold_three(destination, title)
    elif engine_key == "godot":
        files = _scaffold_godot(destination, title)
    else:
        raise ValueError("engine must be one of: html, phaser, three, godot")
    manifest = {
        "version": 1,
        "project_title": title,
        "engine": engine_key,
        "assets": assets,
    }
    _write(destination / "ASSET_MANIFEST.json", json.dumps(manifest, indent=2))
    _write(destination / "CREDITS.md", "# Asset Credits\n\nNo attribution-required assets are currently tracked.\n")
    _write(
        destination / "README.md",
        f"# {title}\n\nPlayable prototype generated by ASSETMCP.\n\n## Controls\n\n- Move: WASD or arrow keys\n- Restart: R\n\n## Run\n\nUse a local static server for browser projects, or open the Godot project in Godot 4.\n\n## Assets\n\nSee `ASSET_MANIFEST.json` and `CREDITS.md`.\n",
    )
    return {"project_path": str(destination), "engine": engine_key, "files": files + ["ASSET_MANIFEST.json", "CREDITS.md", "README.md"]}


def _scaffold_canvas(root: Path, title: str) -> list[str]:
    _write(root / "index.html", f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <link rel="stylesheet" href="src/style.css">
</head>
<body>
  <canvas id="game" width="960" height="540"></canvas>
  <script src="src/game.js"></script>
</body>
</html>
""")
    _write(root / "src" / "style.css", "html,body{margin:0;height:100%;background:#101216;color:#f4f4f4;font-family:Arial,sans-serif}canvas{display:block;margin:auto;max-width:100vw;max-height:100vh;background:#1b2430}\n")
    _write(root / "src" / "game.js", CANVAS_GAME_JS)
    return ["index.html", "src/style.css", "src/game.js"]


def _scaffold_phaser(root: Path, title: str) -> list[str]:
    _write(root / "index.html", f"""<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{title}</title></head>
<body style="margin:0;background:#111">
<script src="https://cdn.jsdelivr.net/npm/phaser@3.90.0/dist/phaser.min.js"></script>
<script src="src/main.js"></script>
</body>
</html>
""")
    _write(root / "src" / "main.js", PHASER_GAME_JS)
    return ["index.html", "src/main.js"]


def _scaffold_three(root: Path, title: str) -> list[str]:
    _write(root / "index.html", f"""<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{title}</title></head>
<body style="margin:0;overflow:hidden;background:#101216">
<script type="module" src="src/main.js"></script>
</body>
</html>
""")
    _write(root / "src" / "main.js", THREE_GAME_JS)
    return ["index.html", "src/main.js"]


def _scaffold_godot(root: Path, title: str) -> list[str]:
    _write(root / "project.godot", f"""; Engine configuration file.
config_version=5

[application]
config/name="{title}"
run/main_scene="res://scenes/main.tscn"

[input]
move_left={{"deadzone":0.5,"events":[]}}
move_right={{"deadzone":0.5,"events":[]}}
move_up={{"deadzone":0.5,"events":[]}}
move_down={{"deadzone":0.5,"events":[]}}
restart={{"deadzone":0.5,"events":[]}}
""")
    _write(root / "scenes" / "main.tscn", GODOT_SCENE)
    _write(root / "scripts" / "main.gd", GODOT_SCRIPT)
    return ["project.godot", "scenes/main.tscn", "scripts/main.gd"]


CANVAS_GAME_JS = r"""const canvas = document.getElementById('game');
const ctx = canvas.getContext('2d');
const keys = new Set();
let state;

function reset() {
  state = {
    menu: true,
    player: { x: 120, y: 260, r: 16, speed: 220 },
    enemy: { x: 780, y: 260, r: 20, vx: -120 },
    score: 0,
    over: false
  };
}

addEventListener('keydown', e => {
  keys.add(e.key.toLowerCase());
  if (state.menu && (e.key === 'Enter' || e.key === ' ')) state.menu = false;
  if (e.key.toLowerCase() === 'r') reset();
});
addEventListener('keyup', e => keys.delete(e.key.toLowerCase()));

function update(dt) {
  if (state.menu || state.over) return;
  const p = state.player;
  const dx = (keys.has('arrowright') || keys.has('d')) - (keys.has('arrowleft') || keys.has('a'));
  const dy = (keys.has('arrowdown') || keys.has('s')) - (keys.has('arrowup') || keys.has('w'));
  p.x = Math.max(p.r, Math.min(canvas.width - p.r, p.x + dx * p.speed * dt));
  p.y = Math.max(p.r, Math.min(canvas.height - p.r, p.y + dy * p.speed * dt));
  const e = state.enemy;
  e.x += e.vx * dt;
  if (e.x < e.r || e.x > canvas.width - e.r) e.vx *= -1;
  state.score += dt;
  if (Math.hypot(p.x - e.x, p.y - e.y) < p.r + e.r) state.over = true;
}

function draw() {
  ctx.clearRect(0, 0, canvas.width, canvas.height);
  ctx.fillStyle = '#243447'; ctx.fillRect(0, 0, canvas.width, canvas.height);
  ctx.fillStyle = '#6ee7b7'; ctx.beginPath(); ctx.arc(state.player.x, state.player.y, state.player.r, 0, Math.PI * 2); ctx.fill();
  ctx.fillStyle = '#f87171'; ctx.beginPath(); ctx.arc(state.enemy.x, state.enemy.y, state.enemy.r, 0, Math.PI * 2); ctx.fill();
  ctx.fillStyle = '#fff'; ctx.font = '20px Arial'; ctx.fillText(`Score: ${Math.floor(state.score)}`, 20, 32);
  if (state.menu || state.over) {
    ctx.fillStyle = 'rgba(0,0,0,.65)'; ctx.fillRect(0, 0, canvas.width, canvas.height);
    ctx.fillStyle = '#fff'; ctx.textAlign = 'center'; ctx.font = '34px Arial';
    ctx.fillText(state.over ? 'Game Over' : 'Prototype Ready', canvas.width / 2, 230);
    ctx.font = '18px Arial'; ctx.fillText(state.over ? 'Press R to restart' : 'Press Enter to start', canvas.width / 2, 270);
    ctx.textAlign = 'left';
  }
}

let last = performance.now();
function loop(now) {
  const dt = Math.min(0.033, (now - last) / 1000); last = now;
  update(dt); draw(); requestAnimationFrame(loop);
}
reset(); requestAnimationFrame(loop);
"""

PHASER_GAME_JS = r"""const config = { type: Phaser.AUTO, width: 960, height: 540, backgroundColor: '#1b2430', scene: { preload, create, update } };
let player, enemy, cursors, score = 0, scoreText, menuText, gameOver = false;
new Phaser.Game(config);
function preload() {}
function create() {
  player = this.add.circle(120, 260, 16, 0x6ee7b7);
  enemy = this.add.circle(780, 260, 20, 0xf87171);
  enemy.vx = -120;
  cursors = this.input.keyboard.createCursorKeys();
  this.input.keyboard.addKeys('W,A,S,D,R,ENTER,SPACE');
  scoreText = this.add.text(20, 20, 'Score: 0', { color: '#fff', fontSize: '20px' });
  menuText = this.add.text(480, 260, 'Press Enter to start', { color: '#fff', fontSize: '30px' }).setOrigin(.5);
}
function update(_, delta) {
  const keys = this.input.keyboard.keys;
  if (Phaser.Input.Keyboard.JustDown(keys.R)) location.reload();
  if (menuText.visible && (Phaser.Input.Keyboard.JustDown(keys.ENTER) || Phaser.Input.Keyboard.JustDown(keys.SPACE))) menuText.visible = false;
  if (menuText.visible || gameOver) return;
  const dt = delta / 1000, speed = 220;
  player.x += ((cursors.right.isDown || keys.D.isDown) - (cursors.left.isDown || keys.A.isDown)) * speed * dt;
  player.y += ((cursors.down.isDown || keys.S.isDown) - (cursors.up.isDown || keys.W.isDown)) * speed * dt;
  player.x = Phaser.Math.Clamp(player.x, 16, 944); player.y = Phaser.Math.Clamp(player.y, 16, 524);
  enemy.x += enemy.vx * dt; if (enemy.x < 20 || enemy.x > 940) enemy.vx *= -1;
  score += dt; scoreText.setText('Score: ' + Math.floor(score));
  if (Phaser.Math.Distance.Between(player.x, player.y, enemy.x, enemy.y) < 36) { gameOver = true; menuText.setText('Game Over - Press R').setVisible(true); }
}
"""

THREE_GAME_JS = r"""import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.178.0/build/three.module.js';
const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(70, innerWidth / innerHeight, .1, 100);
const renderer = new THREE.WebGLRenderer({ antialias: true });
renderer.setSize(innerWidth, innerHeight); document.body.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xffffff, 0x333344, 2));
const player = new THREE.Mesh(new THREE.BoxGeometry(1,1,1), new THREE.MeshStandardMaterial({ color: 0x6ee7b7 }));
const enemy = new THREE.Mesh(new THREE.SphereGeometry(.6), new THREE.MeshStandardMaterial({ color: 0xf87171 }));
scene.add(player, enemy); enemy.position.set(4,0,0); camera.position.set(0,5,8); camera.lookAt(0,0,0);
const keys = new Set(); addEventListener('keydown', e => { keys.add(e.key.toLowerCase()); if (e.key.toLowerCase()==='r') location.reload(); }); addEventListener('keyup', e => keys.delete(e.key.toLowerCase()));
let vx = -2, score = 0, over = false;
function loop(dt=0){ requestAnimationFrame(loop); const step=.016; if(!over){ player.position.x += ((keys.has('d')||keys.has('arrowright'))-(keys.has('a')||keys.has('arrowleft')))*3*step; player.position.z += ((keys.has('s')||keys.has('arrowdown'))-(keys.has('w')||keys.has('arrowup')))*3*step; enemy.position.x += vx*step; if(Math.abs(enemy.position.x)>4) vx*=-1; score+=step; if(player.position.distanceTo(enemy.position)<1.1) over=true; } renderer.render(scene,camera); }
loop();
"""

GODOT_SCENE = """[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://scripts/main.gd" id="1"]

[node name="Main" type="Node2D"]
script = ExtResource("1")
"""

GODOT_SCRIPT = """extends Node2D

var player := Vector2(120, 260)
var enemy := Vector2(780, 260)
var enemy_vx := -120.0
var score := 0.0
var game_over := false

func _process(delta):
    if Input.is_action_just_pressed("restart"):
        get_tree().reload_current_scene()
    if game_over:
        return
    var input := Vector2.ZERO
    input.x = Input.get_axis("move_left", "move_right")
    input.y = Input.get_axis("move_up", "move_down")
    player += input * 220.0 * delta
    enemy.x += enemy_vx * delta
    if enemy.x < 20 or enemy.x > 940:
        enemy_vx *= -1
    score += delta
    if player.distance_to(enemy) < 36:
        game_over = true
    queue_redraw()

func _draw():
    draw_rect(Rect2(Vector2.ZERO, Vector2(960, 540)), Color("#1b2430"))
    draw_circle(player, 16, Color("#6ee7b7"))
    draw_circle(enemy, 20, Color("#f87171"))
    draw_string(ThemeDB.fallback_font, Vector2(20, 32), "Score: %d" % int(score))
    if game_over:
        draw_string(ThemeDB.fallback_font, Vector2(380, 260), "Game Over - restart")
"""
